services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - READ_REPLICA_URL=${READ_REPLICA_URL}
      - DIRECT_URL=${DIRECT_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://54.255.90.86:3000}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-http://54.255.90.86:3000}
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
    volumes:
      - ./public/uploads:/app/public/uploads
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: [ "node", "scripts/worker.js" ]
    depends_on:
      - app
      - redis
    environment:
      - INTERNAL_APP_URL=http://app:3000
      - CRON_SECRET=${CRON_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - READ_REPLICA_URL=${READ_REPLICA_URL}
      - DIRECT_URL=${DIRECT_URL}
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
